print("You need to go on https://example.com/login")
print("")
input("Press ENTER if you've done this.")
print("")
print("On the login page:")
print("Enter ""testuser"" as the username")
print("Enter ""password123"" as the password")
print("")
input("Press ENTER if you've done this.")
print("")
print("It will then take you to https://example.com/dashboard")
print("If all works well, that means the test has passed. If not, the test has failed.")
print("")
input("Press ENTER to finish this.")
